### ISSUE TITLE
Anonymous types not supported, Non-public classes not supported too

### ISSUE THREAD

**Issue by dimzon** [rpgmaker/NetJSON#10] opened 2014-09-01 21:23 UTC
Anonymous types are not supported:
```C#
var obj = new {Foo="bar"}; // You cant's serialize this to JSON
```

Take look @ Dapper.NET IL generation - it can handle both cases (anonymous types and non-public classes)

PS. Talking about polymorphic class instead of StringBuilder - in my tests I see approx 30% performance loss (still near protobuff.net)

**Comment by tanglebones** [comment] 2015-04-06 19:08
If you generate the types to a single assembly we can mark our assemblies InternalsVisibleTo that assembly and avoid the dynamic methods. Currently the emitted code resides in multiple assemblies, each named after the serialization type it contains. Moving them all to a single assembly with a predictable name, like "NetJsonEmitted" would make the InternalsVisibleTo trick easier. This might require pre-declaring the types to be generated. (perhaps add a GenerateTypesTo(string assemblyName, type[] types) call?)

**Comment by rpgmaker** [comment] 2015-04-06 19:25
I guess such a method could work when it comes to generating a single
assembly for all types. But the issue is that there are problem with non
public classes because you cannot read or set values for them since they
are inaccessible.  And your solution will only work if you convert all
private to internal.

I was thinking of generating mix code where setter and getter are dynamic
methods for non public type similar to what I did for messageshark.

**Comment by tanglebones** [comment] 2015-04-06 23:48
Not all private to internal; just those classes we want to serialize/deserialize. In my case those are special classes reversed specifically for representing the json data contracts and they should not be visible as part of the public api for the assembly (the assembly implements json protocols, how it does that is its business). It doesn't solve the private setter problem, but it does solve my use case.

**Comment by rpgmaker** [comment] 2015-04-06 23:51
Go ahead and create another issue in regards to generating a single
assembly for a collection of types.

**Comment by tanglebones** [comment] 2015-04-07 21:33
Added as #50

**Comment by rpgmaker** [comment] 2016-06-21 05:37
Closing issue since it is been hanging for too long. Will create a new issue once ready to implement solution for it.

Thanks,

**Closed by rpgmaker** 2016-06-21 05:37 UTC
Labels: enhancement, wontfix
