### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by hig-dev** [rpgmaker/NetJSON#148] opened 2016-12-29 18:59 UTC
I would like to use your library in my UWP project but unfortunately it seems to be incompatible. Could you add support for the Universal Windows Platform (UAP10)?

**Comment by NimaAra** [comment] 2016-12-29 19:46
_UWP10_ should already be supported as _NetJSON_ supports _netstandard1.6_ and _UWP10_ is compatible with [_netstandard1.4_](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) . I suspect this is due to a problem with the _NuGet_ package. 

Can you obtain the latest _NuGet_ extract the library from the _netstandard1.6_ folder and manually reference it to your project so we can narrow down the problem?

**Comment by hig-ag** [comment] 2016-12-29 20:07
This is what I get when trying to install the lastest nuget:

> Package NetJSON 1.2.1.8 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package NetJSON 1.2.1.8 supports:
>   - net35 (.NETFramework,Version=v3.5)
>   - net40 (.NETFramework,Version=v4.0)
>   - netstandard1.6 (.NETStandard,Version=v1.6)
> One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).

This is what happens when referencing NetJson.Core.dll from the nuget manually.
It throws an exception:

> Exception thrown: 'System.IO.FileLoadException' in mscorlib.ni.dll
> 
> Additional information: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by rpgmaker** [comment] 2016-12-29 21:08
Can add the missing reference and see if it works? Or is the error a compatibility error with system.runtime depends?

**Comment by hig-ag** [comment] 2016-12-29 23:05
No, I can't. I don't know where the problem is. I even tried to use the library in a fresh UWP project. You could check your library yourself with a fresh UWP project.

**Comment by rpgmaker** [comment] 2016-12-29 23:43
OK. I will try it out.

Thanks,

**Comment by rpgmaker** [comment] 2016-12-30 23:33
i tried it out and unfortunately, i could not get the code to compile even though i references the .net core library from nuget. It seem like the Reflection.Emit namespace is missing completely. I also found this: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/8280606-windows-10-uwp-should-support-reflection-emit-for

Not sure if it is still valid.

I also found this link which might help you: http://stackoverflow.com/questions/38315273/cannot-reference-net-core-library-from-uwp

**Comment by rpgmaker** [comment] 2016-12-30 23:36
Without Reflection.Emit been supported properly without downgrading from 1.6 to lower standards, UWP will not work.

**Comment by rpgmaker** [comment] 2017-02-03 03:04
I will be closing this item tomorrow. I cannot do much without the support of Reflection.Emit, let me know if you have concerns.

Thanks,

**Comment by rpgmaker** [comment] 2017-02-05 23:39
Closing. Will create new issue once Reflection.Emit is supported

**Closed by rpgmaker** 2017-02-05 23:39 UTC
