### ISSUE TITLE
Dictionaries aren't serializing to valid JSON

### ISSUE THREAD

**Issue by cuethenoise** [rpgmaker/NetJSON#38] opened 2015-01-19 19:05 UTC
I have a dictionary SkusByPKID serializing as such:
...
"SkusByPKID": {
        218492: {
            "SKUID": 218492,
            "SKU": "F52525000130X30",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X30",
            "UPC": "788029397928",
            "MSRP": 49.99
        },
        218493: {
            "SKUID": 218493,
            "SKU": "F52525000130X32",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X32",
            "UPC": "788029397935",
            "MSRP": 49.99
        },
}, ....

It is missing double quotes around the keys. It should look like this:
...
"SkusByPKID": {
        "218492": {
            "SKUID": 218492,
            "SKU": "F52525000130X30",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X30",
            "UPC": "788029397928",
            "MSRP": 49.99
        },
        "218493": {
            "SKUID": 218493,
            "SKU": "F52525000130X32",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X32",
            "UPC": "788029397935",
            "MSRP": 49.99
        },
},
...

Thanks!

**Comment by rpgmaker** [comment] 2015-01-19 20:13
I thought quotes was just for string. Since you can have a boolean and integer as a key

**Comment by cuethenoise** [comment] 2015-01-19 20:46
All name fields in JSON are string type. The way it serializes a diction you need to treat it as a string. Throw this into jsonlint.com:

{
    "SkusByPKID": {
        218492: {
            "SKUID": 218492,
            "SKU": "F52525000130X30",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X30",
            "UPC": "788029397928",
            "MSRP": 49.99
        },
        218493: {
            "SKUID": 218493,
            "SKU": "F52525000130X32",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X32",
            "UPC": "788029397935",
            "MSRP": 49.99
        }
    }
}
You'll get errors saying it expects a string value.
This is valid:

{
    "SkusByPKID": {
        "218492": {
            "SKUID": 218492,
            "SKU": "F52525000130X30",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X30",
            "UPC": "788029397928",
            "MSRP": 49.99
        },
        "218493": {
            "SKUID": 218493,
            "SKU": "F52525000130X32",
            "RetailPrice": 39.99,
            "ProductID": 674,
            "ProductGroupID": 654,
            "Description": "Men's Propper Lightweight Tactical Pants - Black - 30X32",
            "UPC": "788029397935",
            "MSRP": 49.99
        }
    }
}

I know it's confusing since you think of the key as being any type, but in JSON you have to treat it as a string. LOVE the project by the it is extremely fast!

**Comment by rpgmaker** [comment] 2015-01-19 20:50
That makes a lot of sense. I will update it to always wrap it in quotes. I guess you are right about me thinking about the key in term of storage type.

**Comment by cuethenoise** [comment] 2015-03-19 19:42
I just got the latest Nuget release and it appears this bug isn't fixed. The indexes of the dictionary still have no quotes: 

{
    "LandingPagesByPKID": {
        3196: {
            "LandingPageID": 3196,
            "SEOURL": "shop-all",
            "LandingPageTypeID": 1,
            "SEOTitle": "Shop All",
            "SEODescription": "",
            "SEONoIndex": true,
            "DisplayName": "Shop All",
            "PortalID": 20,
            "NavigationImageFile": "",
            "FeaturedBrandTitle": "",
            "ProductSectionHeader": "",
            "VideoSectionHeader": "",
            "ReviewSectionHeader": "",
            "ShopAllImageName": "",
            "SecondShopAllImageName": "",
            "Description": "",
            "SecondaryDescription": "",
            "ThirdDescription": "",
            "SubFilterDescription": "",
            "ImageFile": "",
            "ProductKitDescription": "",
            "ShowProductCount": true
        }
    }
}

should be:

{
    "LandingPagesByPKID": {
        "3196": {
            "LandingPageID": 3196,
            "SEOURL": "shop-all",
            "LandingPageTypeID": 1,
            "SEOTitle": "Shop All",
            "SEODescription": "",
            "SEONoIndex": true,
            "DisplayName": "Shop All",
            "PortalID": 20,
            "NavigationImageFile": "",
            "FeaturedBrandTitle": "",
            "ProductSectionHeader": "",
            "VideoSectionHeader": "",
            "ReviewSectionHeader": "",
            "ShopAllImageName": "",
            "SecondShopAllImageName": "",
            "Description": "",
            "SecondaryDescription": "",
            "ThirdDescription": "",
            "SubFilterDescription": "",
            "ImageFile": "",
            "ProductKitDescription": "",
            "ShowProductCount": true
        }
    }
}

see the quotes around 3196.

Thanks!

**Comment by rpgmaker** [comment] 2015-03-19 20:23
Sorry. I will look into and get back to you.

Thanks,

**Comment by rpgmaker** [comment] 2015-03-21 01:56
I tried it in the current version and i am not able to reproduce this issue.

public class HolderDictQuote {

        public Dictionary<int, HolderDictDateQuote> IntKeyValue { get; set; }
    }

    public class HolderDictDateQuote {
        public DateTime Date { get; set; }
    }

var cdict = new HolderDictQuote {
                IntKeyValue =
                    new Dictionary<int, HolderDictDateQuote>(){
                        {20, new HolderDictDateQuote{ Date = DateTime.Now}},
                        {40, new HolderDictDateQuote{ Date = DateTime.Now}}
                    }
            };

            var scdict = NetJSON.NetJSON.Serialize(cdict);

            var dcdict = NetJSON.NetJSON.Deserialize<HolderDictQuote>(scdict);

output:

{"IntKeyValue":{"20":{"Date":"\/Date(1426888422)\/"},"40":{"Date":"\/Date(1426888422)\/"}}}

**Comment by rpgmaker** [comment] 2015-03-24 18:38
Closing again since it is not repeatable

**Closed by rpgmaker** 2015-03-24 18:38 UTC
