### ISSUE TITLE
we cannot use this library from F#

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#57] opened 2015-06-02 10:15 UTC
GenerateTypeBuilder throws exception when WriteDeserializeMethodFor creates readMethod for F# record type.

My app uses Newtonsoft.Json with F# model, and it works. I just wanted to test performance gain as you said NetJSON should be 3x quicker that Newtonsoft.Json.

**Comment by rpgmaker** [comment] 2015-06-02 11:38
I am not much of a F# developer. But first thing I will check is are you reading a private or internal class? And if possible can you post your clasd and example here?

**Comment by StefanBelo** [comment] 2015-06-02 12:22
```fsharp
[<NoEquality; NoComparison>]
type BaseApiResponse =
    {
        token : string
        product : string
        status : string
        error : string
    }

    member this.IsSuccess
        with get() = this.status = "SUCCESS"

// I use your liribary to deserialize JSON api request
let data = NetJSON.Deserialize<BaseApiResponse>((Http.ReadBody response))
```
When using Newtonsoft.Json, I had only problems with serialization of enums, so I had to set:

```fsharp
[<JsonConverter(typedefof<StringEnumConverter>)>]
type IncludeItem =
    | ALL = 1
    | DEPOSITS_WITHDRAWALS = 2
    | EXCHANGE = 3
    | POKER_ROOM = 4
```

but no other problems. As you maybe know F# record types are by nature immutable, some other JSON de/serializers required CLIMutable attribute for model types, but not Newtonsoft.Json.

The BaseApiResponse record type/class is by .net seen as:

```c#
	[CompilationMapping(SourceConstructFlags.RecordType), NoComparison, NoEquality]
	[Serializable]
	public sealed class BaseApiResponse
	{
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string token@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string product@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string status@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string error@;
		[CompilationMapping(SourceConstructFlags.Field, 0)]
		public string token
		{
			get
			{
				return this.token@;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 1)]
		public string product
		{
			get
			{
				return this.product@;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 2)]
		public string status
		{
			get
			{
				return this.status@;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 3)]
		public string error
		{
			get
			{
				return this.error@;
			}
		}
		public bool IsSuccess
		{
			get
			{
				return string.Equals(this.status@, "SUCCESS");
			}
		}
		public BaseApiResponse(string token, string product, string status, string error)
		{
			this.token@ = token;
			this.product@ = product;
			this.status@ = status;
			this.error@ = error;
		}
	}
```

So no default constructor, no setter properties. 

I tried to use CLIMutable attribute what should generate setter properties and default construct for BaseApiResponse (what is F# record type), but your library had the same problem with that.

**Comment by StefanBelo** [comment] 2015-06-02 12:34
BaseApiResponse is public class in my model namespace.

**Comment by rpgmaker** [comment] 2015-06-02 12:46
I tried it and it works fine using the following structure.

class Program
    {
        static void Main(string[] args)
        {
            var json = "{\"token\": \"Test\", \"product\": \"Hello World\", \"status\": \"Active\", \"error\": \"none\"}";

            var data = NetJSON.NetJSON.Deserialize<BaseApiResponse>(json);

            var serializeAgain = NetJSON.NetJSON.Serialize<BaseApiResponse>(data);
        }
    }

/*I added setters for the deserialize else you can only serialize since NetJSON does not support non-public members, but it does support field serialize by enabling IncludeFields flag for public fields*/
public sealed class BaseApiResponse
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        internal string tokena;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        internal string producta;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        internal string statusa;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        internal string errora;

        public string token
        {
            get
            {
                return this.tokena;
            }
            set
            {
                this.tokena = value;
            }
        }

        public string product
        {
            get
            {
                return this.producta;
            }
            set
            {
                this.producta = value;
            }
        }

        public string status
        {
            get
            {
                return this.statusa;
            }
            set
            {
                this.statusa = value;
            }
        }
        public string error
        {
            get
            {
                return this.errora;
            }
            set
            {
                this.errora = value;
            }
        }
        public bool IsSuccess
        {
            get
            {
                return string.Equals(this.statusa, "SUCCESS");
            }
        }

        public BaseApiResponse() { } //<-- removing this causes exception

        public BaseApiResponse(string token, string product, string status, string error)
        {
            this.tokena = token;
            this.producta = product;
            this.statusa = status;
            this.errora = error;
        }
    }


If I exclude the default constructor, It give this error message because it is not able to generate the new ctor:

   at NetJSON.NetJSON.GetSerializer[T]()
   at NetJSON.NetJSON.Deserialize[T](String json)
   at TestSerialize.Program.Main(String[] args) in c:\Users\tjbakre\Documents\Visual Studio 2013\Projects\TestSerialize\TestSerialize\Program.cs:line 16
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by StefanBelo** [comment] 2015-06-02 13:33
Thanks, it works for me, at least first api method. When you responded I tried again but without success, so I clean solution and rebuilt again, and it fixed the problem.

What about enum serialization in your library? As I mentioned when using Newtonsoft.Json I had to set: [<JsonConverter(typedefof<StringEnumConverter>)>], to force enum serialization by strings no by numbers. How is it managed with your library?

**Comment by rpgmaker** [comment] 2015-06-02 13:38
As for enum, you have the option to determine how it is serialize as long as it is a public enum. You can use the following option to determine if it uses a string or int.

NetJSON.UseEnumString  = true; 

The default value is set to false, meaning it will generate int. So you want strings then set that to true.

I am guess it will be nice if i include a documentation of the library for common functionality that are not obvious :)

**Comment by rpgmaker** [comment] 2015-06-02 14:01
Can you close this issue once you verify that the Enum solution works?

**Comment by StefanBelo** [comment] 2015-06-02 14:06
I will do so, just testing other parts of api. My model is quite huge, so it will take some time. I will let you know if your library works with f#.

**Comment by StefanBelo** [comment] 2015-06-02 16:09
I have got problem with this JSON:
```json
{"jsonrpc":"2.0","result":{"availableToBetBalance":602.15,"exposure":0.0,"retainedCommission":0.0,"exposureLimit":-10000.0,"discountRate":2.0,"pointsBalance":1181,"wallet":"UK"},"id":1}
```

but not with this one:

```json
{"jsonrpc":"2.0","result":{"currencyCode":"EUR","firstName":"Stefan","lastName":"Surname","localeCode":"en","region":"GBR","timezone":"CET","discountRate":2.0,"pointsBalance":1181,"countryCode":"SK"},"id":1}
```

Here is the code to test:

```c#
namespace ConsoleApplication1
{
    public class ErrorData
    {
        public int code { get; set; }

        public string message { get; set; }
    }

    public class JsonRpcResponse<T>
    {
        public T result { get; set; }

        public ErrorData error { get; set; }

        public bool IsError
        {
            get { return this.error != null; }
        }
    }

    public class AccountFundsResponse
    {
        public double availableToBetBalance { get; set; }

        public double exposure { get; set; }

        public double retainedCommission { get; set; }

        public double exposureLimit { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            string jsonData = "{\"jsonrpc\":\"2.0\",\"result\":{\"availableToBetBalance\":602.15,\"exposure\":0.0,\"retainedCommission\":0.0,\"exposureLimit\":-10000.0,\"discountRate\":2.0,\"pointsBalance\":1181,\"wallet\":\"UK\"},\"id\":1}";

            var serializeAgain = NetJSON.NetJSON.Deserialize<JsonRpcResponse<AccountFundsResponse>>(jsonData);
        }
    }
}

```

**Comment by rpgmaker** [comment] 2015-06-02 16:58
It is interesting that when changed to this:

string jsonData = "{\"jsonrpc\":\"2.0\",\"result\":{\"availableToBetBalance\":602.15,\"exposure\":0.0,\"retainedCommission\":0.0,\"exposureLimit\":-10000.0,\"discountRate\":2.0,\"wallet\":\"UK\",\"pointsBalance\":1181},\"id\":1}";

Then it works.

The issue is the string skipping optimization that i have that does not know when to store skipping therefore it it get stuck in an infinite loop.

You can close this one and open a new issue with infinite loop for string skipping.

**Closed** 2015-06-03 07:17 UTC
