### ISSUE TITLE
"Input is not a valid JSON." exception when de-serializing a string, starting with version 1.0.11

### ISSUE THREAD

**Issue by diazrm** [rpgmaker/NetJSON#81] opened 2015-09-24 16:44 UTC
After updating the NuGet package to 1.0.11 version, an exception raises when trying to de-serialize some JSON strings. For example, the following ones: 

```JSON
{
    "ScreenId": "Error",
    "StepType": "Message",
    "Text": "No se ha encontrado la pagina a la que usted queria ingresar.",
    "Title": "Pagina no encontrada"
}

{
    "ScreenId": "CRM.IDENTIFICADOR",
    "StepType": "Screen",
    "Title": "Identificaci&oacute;n de cliente"
}
```

Both raise the NetJSONInvalidJSONException.

**Comment by rpgmaker** [comment] 2015-09-24 16:57
That is interesting. I will try to look into. The only thing that changes was adding support for using single and double quotes. I must have changed something that is related to detecting it that affect quotes

**Comment by rpgmaker** [comment] 2015-09-27 23:23
I tried the json you provided and I am not able to reproduce the eror. Here is a screenshot showing me testing your json deserialization as both a dictionary and class. Would you be able to give me an example to reproduce it?

![invalidjsonclasssuccess](https://cloud.githubusercontent.com/assets/557807/10125722/21f1bfc0-654d-11e5-91d1-c26fb86b3fd1.png)

**Comment by binis2** [comment] 2015-09-28 10:57
I have similar problem with invalid JSON Exception thou its not related to the JSON content itself. Identical JSONs are parsed fine first time then crashed on the second. My case is quite complex and can't give you a simple example. But it happens when trying to parse JSON in multiple threads so I suspect it's a concurrency problem of some kind. Reverting to version .10  solved the problem.

**Comment by rpgmaker** [comment] 2015-09-28 11:09
Thanks for the insight. I will try to reproduce it

**Comment by rpgmaker** [comment] 2015-09-30 02:32
I am closing this issue since it is not reproduceable. I was able to reproduce the multi-thread issue and it is resolved. Please re-open if issue still exists

Thanks,

**Closed** 2015-09-30 02:31 UTC
