### ISSUE TITLE
Exception class serialization

### ISSUE THREAD

**Issue by Savvkin** [rpgmaker/NetJSON#76] opened 2015-08-06 17:16 UTC
Trying to serialize my Exception DTO to json.
Working with ServiceStack, but not with NetJSON.

```C#
    public class Exception
    {
        public Type ExceptionType { get; private set; }
        public IDictionary Data { get; private set; }
        public string HelpLink { get; set; }
        public Exception InnerException { get; private set; }
        public string Message { get; private set; }
        public string Source { get; set; }
        public string StackTrace { get; private set; }

        public static implicit operator Exception(System.Exception ex)
        {
            if (ex == null) return null;

            var res = new Exception
            {
                ExceptionType = ex.GetType(),
                Data = ex.Data,
                HelpLink = ex.HelpLink,
                InnerException = ex.InnerException,
                Message = ex.Message,
                Source = ex.Source,
                StackTrace = ex.StackTrace
            };

            return res;
        }
    }
```

Looks like a lot of the things are not supported by NetJSON.
The things it doesn't like I found:
- Type `Type`
- Private setter (`private set;`)
- `null` value for `InnerException`

**Comment by rpgmaker** [comment] 2015-08-06 17:36
I cannot serialize Type since there is true represent for it in json except I do what service stack does which is convert it into a full assembly name String containing the type full name and assembly information.

As for private. I currently don't support non public members, it is been in my backlog for a while now.

Best I can do now is make Type work by internally converting it from string back to type as needed.

**Comment by Savvkin** [comment] 2015-08-06 17:48
Thanks for the quick response.

This will be really nice if you add `Type` handling via strings, since I have some inherited classes I need to handle.

Is there any ETA implementing support for private setters?
What is the problem implementing it at least for Serializing? Will it break 'SkipDefaultValue' or something?

**Comment by rpgmaker** [comment] 2015-08-06 18:14
The reason why I did not implement it was because most of the code is depending on generating code that fits in dynamic assembly  rather dynamic methods. I was able to bridge the two in another project  messageshark. I just haven't find time to go through the code to see how much changes I need to make.

It has no effect on skipdefaultvalue in some sense. It could be just a bug caused by it.

Can close this an open a new issue in regards to supporting serialization of Type?

Thanks,

**Closed** 2015-08-07 09:04 UTC

**Comment by rpgmaker** [comment] 2015-08-08 02:58
I have added the support for serialization and deserialization of Type class. I also added your example as a Test without the private setter ofcourse.

If you can, please test and let me know if the result is what you were expecting.

Thanks,
