### ISSUE TITLE
IndexOutOfRangeException Deserializing ISO Date Format

### ISSUE THREAD

**Issue by ortizedgar** [rpgmaker/NetJSON#101] opened 2016-01-14 15:44 UTC
Hi,

When I'm trying to deserialize an object with a DateTime serialized in ISO format I get an IndexOutOfRangeException.

Example: 

JSon.Deserialize<LoggingData>(JSon.Serialize<LoggingData>(objectNotSerialized));

System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
Result StackTrace:	
en NetJSON.NetJSON.FastStringToDate(String value)
   en LoggingDataClass.ExtractDateTime(Char* , Int32& )
   en LoggingDataClass.SetLoggingData(Char* , Int32& , LoggingData , String )
   en LoggingDataClass.CreateClassOrDictLoggingData(Char* , Int32& )
   en LoggingDataClass.ReadLoggingData(String )
   en LoggingDataClass.Deserialize(String )
   en NetJSON.NetJSON.Deserialize[T](String json)

The exception is in NetJSON.cs - Line 3766, utcOffsetText is string.Empty

Thanks

**Comment by rpgmaker** [comment] 2016-01-14 20:14
Hi, are you using the current version in nuget or latest in source control. Will it be possible to give me a sample data or code for me to reproduce the issue.

Thanks,

**Comment by ortizedgar** [comment] 2016-01-15 14:15
Hi, I'm using version 1.0.15.5
I send the code attached.
Thank you.

[Test..txt](https://github.com/rpgmaker/NetJSON/files/91982/Test.txt)

**Comment by rpgmaker** [comment] 2016-01-15 15:01
Thanks. I will try to get to it as soon as I can.

Thanks,

**Comment by rpgmaker** [comment] 2016-01-17 21:39
The issue is with your format, your year is 1 digit character, it should be 4 digit as described here: http://www.iso.org/iso/home/standards/iso8601.htm

**Comment by rpgmaker** [comment] 2016-01-19 22:52
Closing issue because it working as expected.

**Closed by rpgmaker** 2016-01-19 22:52 UTC
