### ISSUE TITLE
Serialized DateTime can't be Deserialized (ISO Format)

### ISSUE THREAD

**Issue by VictorySquareAdmin** [rpgmaker/NetJSON#55] opened 2015-05-20 00:38 UTC
This string is generated by the library when a corresponding DateTime object is serialized (using ``NetJSON.NetJSONDateFormat.ISO``):

```
2015-5-20T0:12:48.695Z
```

But throws the "Not a valid DateTime string" when deserializing.

I tried changing the regex to:

```
(\d){4}-(\d){1,2}-(\d){1,2}T(\d){1,2}:(\d){1,2}:(\d){1,2}.(\d){1,3}Z
```

IE:

```CSharp
NetJSON.NetJSON._dateISORegex = new System.Text.RegularExpressions.Regex(@"(\d){4}-(\d){1,2}-(\d){1,2}T(\d){1,2}:(\d){1,2}:(\d){1,2}.(\d){1,3}Z", NetJSON.NetJSON._dateISORegex.Options);
```

Running the regex in isolation works, it recognizes the string. But deserializing still fails.

**Comment by rpgmaker** [comment] 2015-05-20 01:35
Are you trying to serialize a class with a property of type DateTime or are you serializing just a DateTime object?

**Comment by rpgmaker** [comment] 2015-05-20 01:45
I tried the following and I am not getting any error with date time.


    public class TestClassWithDate {
        public DateTime CreateDate { get; set; }
    }


    NetJSON.NetJSON.DateFormat = NetJSON.NetJSONDateFormat.ISO;

     var json =  NetJSON.NetJSON.Serialize(new TestClassWithDate { CreateDate = DateTime.Now });

     var jsonResult = NetJSON.NetJSON.Deserialize<TestClassWithDate>(json);

**Comment by rpgmaker** [comment] 2015-05-20 14:07
Can you give me an example that reproduce this issue?

Thanks,

**Comment by rpgmaker** [comment] 2015-05-24 01:08
I am going to close this issue since I cannot reproduce it. But you are welcome to reopen it if you can recreate it with an example. Thanks

**Closed by rpgmaker** 2015-05-24 01:08 UTC
