### ISSUE TITLE
can not Deserialize struct

### ISSUE THREAD

**Issue by flyzb618** [rpgmaker/NetJSON#188] opened 2018-01-07 11:58 UTC
when I Deserialize struct object,there is erro . Who can help me ?
`struct SimpleObject
    {
        public int ID;
        public string Name;
        public string Value;
    }`

**Comment by rpgmaker** [comment] 2018-01-07 12:41
I will look into it. Thanks

**Comment by rpgmaker** [comment] 2018-01-09 11:04
That is the specific error you are getting? Thanks

**Comment by rpgmaker** [comment] 2018-01-09 22:44
I tried to reproduce the issue and I can't. Are you using the latest code?

```
struct SimpleObjectStruct
    {
        public int ID;
        public string Name;
        public string Value;
    }
```

```
 [TestMethod]
        public void TestSimpleStruct()
        {
            var settings = new NetJSONSettings();
            var data = new SimpleObjectStruct() { ID = 10, Name = "Test", Value = "Tester" };
            var json = NetJSON.Serialize(data, settings);
            var data2 = NetJSON.Deserialize<SimpleObjectStruct>(json, settings);

            Assert.AreEqual(data.ID, data2.ID);
            Assert.AreEqual(data.Name, data2.Name);
            Assert.AreEqual(data.Value, data2.Value);
        }
```

**Comment by rpgmaker** [comment] 2018-01-29 06:29
Any update? If not, i could close the issue if it is no longer an issue.

Thanks,

**Comment by rpgmaker** [comment] 2018-02-06 04:35
I will go ahead and close this this issue since there is no updates. Please reopen if this is still a problem.

Thanks,

**Closed** 2018-02-06 04:35 UTC
