### ISSUE TITLE
net core 2.0 - infinite loop

### ISSUE THREAD

**Issue by stormdust** [rpgmaker/NetJSON#178] opened 2017-09-15 09:26 UTC
Just try to this NetJSON.NetJSON.Deserialize<T>(json);
of
[{"VehicleID":"21144","TrackUrl":""}]

infinite loop and cpu at 100%

build 1.2.1.9 and 10

**Comment by rpgmaker** [comment] 2017-09-15 12:36
What are deserializing to? Could you also try it without an empty string?

Thanks,

**Comment by rpgmaker** [comment] 2017-09-17 16:14
Hi,

Do you have any additional details about the failure?

Thanks,

**Comment by stormdust** [comment] 2017-09-18 07:42
i just invoke this NetJSON.NetJSON.Deserialize("[{\"VehicleID\":\"21144\",\"TrackUrl\":\"\"}]");
and it locks the core 2.0 process dotnet.exe, tested in windows 10 and 2012 instances.

**Comment by rpgmaker** [comment] 2017-09-18 11:37
Thanks for the information. Will look into it. In the meantime, could you remove the field with empty string or fill it in. And let me know the results.

Thanks,

**Comment by stormdust** [comment] 2017-09-21 09:08
The problem is on the int with quotes on vehicle id value.

"[{"VehicleID":"21144","TrackUrl":""}]"); loop
"[{"VehicleID":21144,"TrackUrl":""}]"); dont loop

**Comment by rpgmaker** [comment] 2017-09-21 22:50
I tried the code in a version lesser than 2.0 with the string version that is supposed to loop. But it does not loop for me, it works fine.

Could you try the latest code in the repo? I might have fixed it.

Thanks,

**Comment by rpgmaker** [comment] 2017-10-16 02:28
Any updates on this test?

**Comment by stormdust** [comment] 2017-10-16 07:29
no, didnt test it more.

**Comment by rpgmaker** [comment] 2017-10-24 01:18
The best I could do for now is throw an exception to short-circuit the infinite loop. I don't have support for mismatch types at the moment, because I only process string in a forward only matter and do not read the stream backward.

I will consider supporting it in the future. So for now, I will be closing this issue since it is as designed. Feel free to create a new issue requesting for support of type mismatch.

Thanks,

**Comment by rpgmaker** [comment] 2017-10-24 01:20
If you would like to volunteer to help me resolve this issue I would be glad.

**Closed by rpgmaker** 2017-10-24 01:20 UTC
Labels: bug, enhancement, help wanted
