### ISSUE TITLE
NetJSON PCL is not working

### ISSUE THREAD

**Issue by minhdqvn** [rpgmaker/NetJSON#125] opened 2016-08-11 03:33 UTC
PCL project build with many errors ()

**Comment by rpgmaker** [comment] 2016-08-11 03:35
PCL is not meant to build. It is not implemented yet. I only recently
added  .net core support.

Thanks,

**Comment by minhdqvn** [comment] 2016-08-11 03:37
Do you have the plan about it?

**Comment by rpgmaker** [comment] 2016-08-11 03:42
I have somewhat of a plan to look into later in the future once reflection emit is supported. Without emit is it difficult to support PCL without a full rewrite that is based on dynamic methods. Which is why I don't currently support it.

Thanks,

**Comment by rpgmaker** [comment] 2016-08-20 02:30
Update. Now that I have both dynamic methods and assemblies co-existing to support non-public types. When I have enough time to go through all the missing method in PCL, i will fully implement it.

Thanks,

**Comment by rpgmaker** [comment] 2016-08-26 02:50
Do you want to help me in resolving some of the error message caused by using PCL compilation? I think so far, i have about 200 errors that needs to be resolve to make it compile for PCL

Thanks,

**Comment by minhdqvn** [comment] 2016-09-04 03:00
Sure, I will support to resolve them. Let me know about my task.

**Comment by wmjordan** [comment] 2016-09-04 10:58
@minhdqvn Currently I am working on #132 . Hopefully I would manage to find some hours. Afterwards, we could process with this. The biggest problem of PCL support is that it lacks classes, such as `TypeBuilder`, to support dynamic IL emission.

**Comment by NimaAra** [comment] 2016-09-04 11:34
@wmjordan Why not target `.NET Core` ([Net Standard 1.3](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)) instead of `PCL` then you can take advantage of [Managed Reflection](https://github.com/jfrijters/Managed.Reflection) with full Emit support and the `TypeBuilder`.

**Comment by rpgmaker** [comment] 2016-09-04 11:47
In regards to pcl and using dynamic type instead of the builder. You can put the #if NET_PCL in the get serializer method so that it will only use dynamic method option that is currently supported for non public types. And then you will have a lot more of #if check to switch tell it to onlu use the builder which is most of the code.

But as Nima mention try .net core too if possible

Thanks,

**Comment by wmjordan** [comment] 2016-09-04 14:09
@NimaAra You are right.
@rpgmaker It appears that PCL does not support unsafe code, which is another problem. I'd love to work with .NET Core instead.

**Comment by rpgmaker** [comment] 2016-09-04 14:22
The current netjson has support for .net core since the last two versions. Here 
https://github.com/rpgmaker/NetJSON/releases/tag/v1.2.1.0

Thanks,

**Comment by rpgmaker** [comment] 2016-09-04 14:27
In regards to pcl supporting unsafe, you can use profile 78 (.NET 4.5, Windows Store 8, Windows Phone 8).

Thanks,

**Comment by wmjordan** [comment] 2016-09-04 14:47
I'd just made a pull request for #132. I am also attempting to eliminate some conditional compilation directives to make the code look better.
Now less public methods are exposed by the NetJSON class (they were moved to `NetJSON.Internals.SerializerUtilities`).

The renaming of `NetJSON.NetJSON` to another name was not done yet.

**Comment by rpgmaker** [comment] 2016-09-20 01:28
Is this issue still relevant since there is a support for .net core now? if it is let me know else I might close it by the end of the week. 

Thanks,

**Comment by rpgmaker** [comment] 2016-09-25 05:35
Closing assuming. Net core. Reopen if still needed.

Thanks,

**Closed by rpgmaker** 2016-09-25 05:35 UTC
Labels: enhancement, help wanted
