### ISSUE TITLE
Cannot deserialize immutable models.

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#116] opened 2016-06-21 07:33 UTC
Given an immutable model as:

```csharp
public sealed class Person
{
    public Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { get; }
    public int Age { get; }
}
```
The following test fails:
```csharp
[TestMethod]
public void TestImmutableModel()
{
    var model = new Person("John", 12);

    var json = NetJSON.Serialize(model);

    var settings = new NetJSONSettings {IncludeTypeInformation = true};
    var deserializedModel = NetJSON.Deserialize<Person>(json, settings);
    Assert.AreEqual(deserializedModel.Name, "John");
    Assert.AreEqual(deserializedModel.Age, 12);
}
```

**Comment by rpgmaker** [comment] 2016-06-21 07:34
Thanks

**Comment by rpgmaker** [comment] 2016-06-26 01:12
Btw, the class you posted is invalid code. You basically defined a readonly field. You cannot set the properties in the constructor unless they have a private setter. Is that what you are expecting? If you are using 4.6.2, maybe it is inferred

I am going to add support for non-public property setter only since it is the only issue in this scenario assuming that your version of .net is inferring the private setters

Thanks,

**Comment by rpgmaker** [comment] 2016-06-26 03:09
Please test again.

Thanks,

**Comment by NimaAra** [comment] 2016-06-26 10:50
Hi, 

The code is valid C# 6 please refer to: [Getter only auto-properties](https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6)

Your changes add support for private setters (not truly immutable models) e.g:

```csharp
public sealed class Person
{
    public Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { get; private set;}
    public int Age { get; private set;}
}
```

But not the new getter only properties:

```csharp
public sealed class Person
{
    public Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { get; }
    public int Age { get; }
}
```
It also does not support the following model:

```csharp
public sealed class Person
{
    private readonly string _myName;
    private readonly int _myAge;

    public Person(string name, int age)
    {
        _myName = name;
        _myAge = age;
    }

    public string Name => _myName;
    public int Age => _myAge;
}
```
or:

```csharp
public sealed class Person
{
    private readonly string _myName;
    private readonly int _myAge;

    public Person(string name, int age)
    {
        _myName = name;
        _myAge = age;
    }

    public string Name
    {
        get
        {
            return _myName;
        }
    }

    public int Age
    {
        get
        {
            return _myAge;
        }
    }
}
```

Sorry for being a pain but I would like to cover all the valid scenarios a user would be trying.

**Comment by rpgmaker** [comment] 2016-06-26 12:44
No problem. The first issue, I don't think anyone for deserialization calls the non default constructor for you since order of property can be inferred for the parameters. The definition of the non default constructor is great for creating an instance to serialize not to be confused for deserialization. The current scenario will work with getter as it is because the getter defines a public get_XXX for the property even though it is accessing a non public backing field.

The issue is that you want me to be able to set readonly fields outside of a constructor.

I will have to think about it a little bit after complete the other open issue today.

**Comment by rpgmaker** [comment] 2016-06-26 12:48
Even with the auto get properties in c# 6. It is still following the rules of properties by creating backing fields for you when setters does not exists. Which could be private or internal mixed with readonly keyword. Can you help me post the decompiled code for a valid c# that has only a getter but also allows you to access the hidden setter beyond the constructor?

Thanks,

**Comment by NimaAra** [comment] 2016-06-26 13:04
Sure you are right in saying that they create a backing field. I am not suggesting that getter only properties can/should be set outside of a constructor. I was assuming that in your fix for this feature you were looking at the non-default constructor of the model and inject the arguments there.

FYI, [HERE](http://stackoverflow.com/a/23017892/1226568) is how JSON.NET is doing the same using the `[JsonConstructor]` and injecting the arguments to the non-default constructor.

**Comment by rpgmaker** [comment] 2016-06-26 13:18
If the class is from a external component then the feature will not work I suppose without having to inherit the class to pass the args from your constructor to their or without modification of the code to have knowledge of it.

So in summary you want me to implement an attribute for constructor or automatically invoke the constructor when it is available?

Thanks,

Thanks,

**Comment by NimaAra** [comment] 2016-06-26 13:26
I am not sure if I understand what you mean with regards to the external component.

As with the option between an attribute or invoking the non-default constructor I am fine with either, I suppose if calling the non-default constructor by default could impact the performance then having to explicitly define the attribute is perfectly acceptable. 

I guess it is best for you to decide as the owner of the library you have a better idea of how you want to shape it going forward.

**Comment by rpgmaker** [comment] 2016-06-26 13:39
I was referring to third party libraries that might similar definition of class that you cannot change to include attributes. In my case, using attribute or not does not really changed anything since in regards to performance since everything will be emitted inline once at compilation time. 

The only real problem is that I currently construct the class before I set the fields and properties. I will have to change it to inject the values for the constructor parameters. 

Will have to think of a way to do it without too much cost and get back to you.

Do let me know if you have any idea of the best way to go about implementing it.

Thanks,

**Comment by NimaAra** [comment] 2016-06-26 13:53
Okay now I understand thank you for the clarification, yes that is a valid concern but then as you mentioned one would have to inherit from the model unless it is sealed. 

I will have a think as well on my side.

**Comment by rpgmaker** [comment] 2016-06-26 14:08
Can you help me run ilspy or reflector on your class that only has a getter in c# 6. I want to see what the generated code looks like. 

I want to see if there is a specific naming convention used for the readonly fields such as _<prop name>.

If there is then I can infer it in my code and also set a requirement to do same instead of depending on constructor definition. I can easily use reflection to set the readonly fields.

Thanks,

**Comment by NimaAra** [comment] 2016-06-26 14:17
Below are the various models with their corresponding IL:

```csharp
public sealed class Person
{
    public Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { get; private set; }
    public int Age { get; private set; }
}
```
**IL:**
```
Person.get_Name:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person.<Name>k__BackingField
IL_0006:  ret         

Person.set_Name:
IL_0000:  ldarg.0     
IL_0001:  ldarg.1     
IL_0002:  stfld       UserQuery+Person.<Name>k__BackingField
IL_0007:  ret         

Person.get_Age:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person.<Age>k__BackingField
IL_0006:  ret         

Person.set_Age:
IL_0000:  ldarg.0     
IL_0001:  ldarg.1     
IL_0002:  stfld       UserQuery+Person.<Age>k__BackingField
IL_0007:  ret         

Person..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  nop         
IL_0008:  ldarg.0     
IL_0009:  ldarg.1     
IL_000A:  call        UserQuery+Person.set_Name
IL_000F:  nop         
IL_0010:  ldarg.0     
IL_0011:  ldarg.2     
IL_0012:  call        UserQuery+Person.set_Age
IL_0017:  nop         
IL_0018:  ret
```

```csharp
public sealed class Person
{
    public Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { get; }
    public int Age { get; }
}
```
**IL**:
```
Person.get_Name:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person.<Name>k__BackingField
IL_0006:  ret         

Person.get_Age:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person.<Age>k__BackingField
IL_0006:  ret         

Person..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  nop         
IL_0008:  ldarg.0     
IL_0009:  ldarg.1     
IL_000A:  stfld       UserQuery+Person.<Name>k__BackingField
IL_000F:  ldarg.0     
IL_0010:  ldarg.2     
IL_0011:  stfld       UserQuery+Person.<Age>k__BackingField
IL_0016:  ret 
```

```csharp
public sealed class Person
{
    private readonly string _myName;
    private readonly int _myAge;

    public Person(string name, int age)
    {
        _myName = name;
        _myAge = age;
    }

    public string Name => _myName;
    public int Age => _myAge;
}
```

**IL**:
```
Person.get_Name:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person._myName
IL_0006:  ret         

Person.get_Age:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person._myAge
IL_0006:  ret         

Person..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  nop         
IL_0008:  ldarg.0     
IL_0009:  ldarg.1     
IL_000A:  stfld       UserQuery+Person._myName
IL_000F:  ldarg.0     
IL_0010:  ldarg.2     
IL_0011:  stfld       UserQuery+Person._myAge
IL_0016:  ret 
```

```csharp
public sealed class Person
{
    private readonly string _myName;
    private readonly int _myAge;

    public Person(string name, int age)
    {
        _myName = name;
        _myAge = age;
    }

    public string Name
    {
        get
        {
            return _myName;
        }
    }

    public int Age
    {
        get
        {
            return _myAge;
        }
    }
}
```
**IL**:
```
Person.get_Name:
IL_0000:  nop         
IL_0001:  ldarg.0     
IL_0002:  ldfld       UserQuery+Person._myName
IL_0007:  stloc.0     
IL_0008:  br.s        IL_000A
IL_000A:  ldloc.0     
IL_000B:  ret         

Person.get_Age:
IL_0000:  nop         
IL_0001:  ldarg.0     
IL_0002:  ldfld       UserQuery+Person._myAge
IL_0007:  stloc.0     
IL_0008:  br.s        IL_000A
IL_000A:  ldloc.0     
IL_000B:  ret         

Person..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  nop         
IL_0008:  ldarg.0     
IL_0009:  ldarg.1     
IL_000A:  stfld       UserQuery+Person._myName
IL_000F:  ldarg.0     
IL_0010:  ldarg.2     
IL_0011:  stfld       UserQuery+Person._myAge
IL_0016:  ret         
```

**Comment by NimaAra** [comment] 2016-06-26 14:19
And here's the model whose field names do not include `_`:

```csharp
public sealed class Person
{
    private readonly string myName;
    private readonly int myAge;

    public Person(string name, int age)
    {
        myName = name;
        myAge = age;
    }

    public string Name => myName;
    public int Age => myAge;
}
```
**IL**:

```
Person.get_Name:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person.myName
IL_0006:  ret         

Person.get_Age:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+Person.myAge
IL_0006:  ret         

Person..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  nop         
IL_0008:  ldarg.0     
IL_0009:  ldarg.1     
IL_000A:  stfld       UserQuery+Person.myName
IL_000F:  ldarg.0     
IL_0010:  ldarg.2     
IL_0011:  stfld       UserQuery+Person.myAge
IL_0016:  ret  
```

**Comment by rpgmaker** [comment] 2016-06-26 14:25
Based on the generated cil. I will have to use it via the constructor for it to work in all case.

Thanks for help. I will look into it and try to avoid using attribute 😀

**Comment by rpgmaker** [comment] 2016-07-11 00:45
sorry i have not got a chance to look into this issue, was busy with personal stuff. Will look into it this coming week.

Thanks,

**Comment by NimaAra** [comment] 2016-07-11 06:39
Thanks for the update no worries we are all busy with life :-)

**Comment by wmjordan** [comment] 2016-07-14 06:56
About the private members, I studied the source code and see that `DynamicMethods` were used to access private setters in properties. I think it is possible to directly access the underlining private field without the property setter by emitting a `Stfld` operation code.

**Comment by wmjordan** [comment] 2016-07-14 07:09
For @NimaAra 's cases, the parametric constructors must be taken into consideration. Since the programmers usually use the constructor to verify or prepare the data. For instance, 

````C#
public sealed class Person
{
    private readonly string myName;
    private readonly int myAge;

    public Person(string name, int age)
    {
        if (String.IsNullOrEmpty(name))
             throw new ArgumentException("name could not be empty.");
        if (age < 0)
             throw new ArgumentException("age could not be negative.");
        myName = name;
        myAge = age;
    }

    public string Name => myName;
    public int Age => myAge;
}
````
And it is very possible that a type can have multiple constructors, with or without parameters.
We shall provide some instruction mechanism to specify which constructors shall be used. For instance,

````C#
var settings = new NetJSONSettings {IncludeTypeInformation = true};
settings.UseParametricConstructorFor<Person>(typeof(string), typeof(int));
settings.UseParametricConstructorFor<Company>(typeof(int));
var deserializedModel = NetJSON.Deserialize<Person>(json, settings);
````

**Comment by NimaAra** [comment] 2016-07-14 08:27
@wmjordan I agree with your comment pointing out the need to consider what happens in the constructor, the user might very well have logic that may affect the values going in.

As to how the user should go about specifying the constructor I very much like to leave this up to @rpgmaker to see what he comes up with but of course we can always provide feedback to ensure a smooth experience.

**Comment by rpgmaker** [comment] 2016-07-14 12:20
@wmjordan, I cannot use stfld because for private Property i cannot infer the name of the backing field in any scenario which include when dev create it own field vs when auto getter/setter is been used.

In regards to constructor selection, the use of NetJSONSettings to control it will not sufficient because it will require reflection to make use of the information right at the point of deserialization. In order to preserve the performance overall, I will need to inline the selection of constructor within the deserialization method and simply pick any constructor that has names closer to class fields/properties. Picking the class automatically can also allow me to pick a constructor that might have a complex parameter which can possibly deserialize all the fields/properties of the class to avoid the need to individual parameters. The type information definition does not really always help because i can have two string parameter for my constructor and would not really help me in picking which is correct and ordering of the fields/properties within the class cannot be relied on either.

At the moment, i am looking at mostly picking constructor with the most parameters closer to the number of fields/properties in the class. I am trying to avoid introduction of another attribute. Let me know if you have any other idea or objection

Thanks,

**Comment by wmjordan** [comment] 2016-07-14 14:27
_Picking constructor with the most parameters closer to the number of fields/properties in the class_ is a natural approach. It is great and can be used easily without manual manipulation, most of the time. However, when we meet with a class which has more than one constructors, both of which have the same number of parameters, the result can be unpredictable. For instance, the following is a not-so-well-designed class:
````C#
public class Person {
   public string Name { get; private set; }
   public int? Age { get; private set; }
   public string ReasonForUnknownAge { get; private set; }
   public Person (string name, int age) { ... } // age is known
   public Person (string name, string reasonForUnknownAge) { ... } // age is unknown, for some reason
}
````
And the following manually forged JSON data can make the deserializer have a hard time to choose the right constructor, since the three fields match the two constructors.
````Javascript
{ "name": "boss", "age": 0, "reasonForUnknownAge": "he is the boss" }
`````

Is it possible to apply the `UseParametricConstructorFor` method on the same target type multiple times to specify preferred constructor overloads (The firstly specified constructor overload has a higher precedence)? So, for the above example, the programmer can instruct the `(string name, string reasonForUnknownAge)` constructor overload has a higher precedence (when a reason for unknown age is given, the age is ignored).

If there are not enough fields for the preferred constructors, it is possible to replace the missing parameter with a `default` value of the `ParameterType`, or fall back to the get an uninitialized instance. I personally prefer the first approach since the programmer can have a chance to force the object is checked and properly initialized.

The rest problem is to deserialize other JSON fields which are not deserialized. We shall mark the

**Comment by rpgmaker** [comment] 2016-07-18 03:18
In the case of having two constructor which has same number of parameters. I will just choose the last one. As for parameters that are remaining which does not belong to the constructor, I can always set them even though the class have private setters. Which will somewhat help the scenario above where you have two constructor. At the end of the processing all the fields will be set no matter what.

I am currently changing the code to use the last matching constructor, because I am trying to avoid more attributes and also trying to avoid runtime checks and preferable inline all the logic that will do the construction. I should have it checked in hopefully in 4 days or less after testing it out.

Let me know me if you have any comment or objection.

Thanks,

**Closed** 2016-07-24 05:49 UTC
Labels: enhancement

**Comment by rpgmaker** [comment] 2016-07-24 05:51
Please test again. It does not have the best performance, but should be better than json.net and other. I currently do not use any attribute. I just pick the last one with the most parameters. The scenario you specified above works for even with conflicting numbers of parameters because it will still set the missing parameter in either one after creating the constructor.

Thanks,

**Comment by NimaAra** [comment] 2016-07-24 22:03
I just did some basic tests and it works great although I have not benchmarked it thoroughly.

On a separate note and unrelated to your latest changes, I noticed a very concerning behaviour.

After creating a not so complicated model and serializing it with **_NetJson,_** I discovered the library was randomly skipping and ignoring properties therefore creating invalid _JSON_; However the same model was correctly serialized with _**JIL**_ or **_JSON.NET_**.

Unfortunately I cannot share the model as is but I am planning to recreate this and open an issue.

Thanks.

**Comment by rpgmaker** [comment] 2016-07-24 22:08
When you say invalid json do you mean unparsable or json with missing data? Do you happen to be using serialize method with netjson settings as a parameter? If not that could be the issue because the state of setting used without the explicitly passing is shared and can be modified by any thread since it is static.

Thanks,

**Comment by NimaAra** [comment] 2016-07-24 22:19
I mean valid _JSON_ with missing properties. And I am using serialize with a _**NetJson**_ settings but this is not a threading issue it is a simple test running on the main thread creating the objects then serializing. So for example if there is:

```csharp
public class Parent
{
    public Child[] Children { get; set; }
}
public class Child
{
    public string Name { get; set; }
    public int Age { get; set; }
    public string Description { get; set; }
    public string Adress { get; set; }
}
```
And when the object graph is populated, for some of the values in the produced _JSON_ properties are missing randomly, so for example the first item in the array is missing **Age**, then next 4 are good and the 5th one is missing the **Address** etc..

All the items have identical values so it has nothing to do with the actual data. Like I said I am trying to write a test replicating this with a set of models that I can share with you.

**Comment by rpgmaker** [comment] 2016-07-24 22:26
That is interesting. Never seen that before, do let know once you create an example. Any chance you are using case insensitive property name? If you are be sure to set case sensitive to false.

Thanks,

**Comment by NimaAra** [comment] 2016-07-24 22:29
No, I was not messing with anything other than the below:

```csharp
var settings = new NetJSONSettings
{
    Format = NetJSONFormat.Default,
    UseStringOptimization = false
};
```
And of course I have tried `true` for the string optimization as well with no effect :-( 

Okay let me see if I can reproduce this with another model.

**Comment by rpgmaker** [comment] 2016-07-24 22:33
String optimization option is not for performance improvement that is optional, it simply enable skipping the character by character processing of json. The option is there to turn it off due any bug.

Look forward to your example.


Thanks,

**Comment by NimaAra** [comment] 2016-07-24 22:36
Okay I got it! opening an issue now...
