### ISSUE TITLE
AnonymousType is not supported

### ISSUE THREAD

**Issue by zyz** [rpgmaker/NetJSON#96] opened 2015-12-10 09:39 UTC
var obj = new { Id=1,Name="Test" };
var json = NetJSON.NetJSON.Serialize(obj);

Non-Public Types is not supported yet 
In C#, AnonymousType is powerful.
If don't support, very bad

**Comment by rpgmaker** [comment] 2015-12-10 12:54
Still working on the support of anonymous types. Might take a bit. I can easily support a basic anonymous type but the issue is supporting complex ones.


Thanks,

**Comment by rpgmaker** [comment] 2015-12-24 06:07
Closing this issue because it is a duplicate of https://github.com/rpgmaker/NetJSON/issues/10 

Thanks,

**Closed by rpgmaker** 2015-12-24 06:07 UTC
