### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dlonagh** [rpgmaker/NetJSON#72] opened 2015-07-30 18:45 UTC
Hello, rpgmaker.

I've been looking for some great fast JSON libraries.
A game I'm developing reads JSON files and loads them into game objects.

I'm having hard time finding the documentation for NetJSON, though.
List of examples and functions available for it.

Where can I find them?

**Comment by rpgmaker** [comment] 2015-07-30 19:19
I will create one tonight. I have been thinking of doing so foe a while now.

**Comment by dlonagh** [comment] 2015-07-30 20:39
Great to know! I'm looking forward to it!

**Comment by rpgmaker** [comment] 2015-07-30 23:34
I just added a quick guide to start here: https://github.com/rpgmaker/NetJSON/wiki/Quick-Guide

I will add more in the future. Let me know if that helps.

Thanks,

**Comment by dlonagh** [comment] 2015-07-30 23:46
What does Deserialize<T>(TextReader reader) return?

If you deserialize a json file, what does that deserialize them into? An array of object?
Does NetJSON automatically convert json string into a string object, and json int (number) into an integer?

**Comment by rpgmaker** [comment] 2015-07-30 23:56
It returns the constraint T type. So for example,

Deserialize[Foo](new StringReader()) --> Return Foos

Deserialization is depending on the methods you use. If you use the one with [T] then it will return whatever you specific in the constraint. If you want to return a list, then you specific List[WhatTypeNameIs] or WhatTypeNameIs[] assuming your json is a array "[...]".

If you want it to automatically select the type for you when you don't have a specific predefined Class Type, then you should use DeserializeObject(string json). Because it will automatically select the type and put it as object. For example, 
{"ID" : 10, "Name", "Test"} will automatically be converted into the correct Dictionary[string, object] where ID and Name are the keys are 10 and "Test" are corresponding values for each key. Each value in this scenario will be convert to type of object for the value aspect of the dictionary.

While using the DeserializeObject, if it detects an Array or Dictionary it will recursively convert them to the correct type and cast to type object for you.

Thanks,

**Comment by dlonagh** [comment] 2015-07-31 00:34
Hm. Sorry. I don't really understand how it works.

If I had {"ID": 10, "Name": "Test"} json data, and I specify "public class MyObject { string objID; string objname }" as T, are you saying NetJSON can do just that?

I don't believe so. Can you give me some examples and how it actually works?
Thanks.

**Comment by rpgmaker** [comment] 2015-07-31 00:40
if you want to deserialize {"ID": 10, "Name": "Test"}. You have two ways to do so. You can use

public MyClass {
    public int ID {get;set;}
    public string Name {get;set}
}

Then do the following:

var obj = NetJSON.Deserialize<MyClass>(json);

or you can do this

Dictionary[string, object] = NetJSON.DeserializeObject(json) as Dictionary[string, object] 

This one will automatically map the json key/value to the correct types in the dictionary.

Thanks,

**Comment by dlonagh** [comment] 2015-07-31 00:55
Your explanation seems to be heavily lacking.

How does "var obj = NetJSON.Deserialize(json);" know about MyClass when the statement doesn't mention anything about MyClass?
And what's json? Is it a string? a custom json object?
AFAIK, There is no such thing as Deserialize() that accepts one argument.

**Comment by rpgmaker** [comment] 2015-07-31 00:59
The issue is GitHub is messing up my formatting.

i wrote NetJSON.Deserialize{MyClass}(json) . Replace { and } with the less and greater than symbol.

**Comment by rpgmaker** [comment] 2015-07-31 00:59
Json is just a regular string

**Comment by dlonagh** [comment] 2015-07-31 01:01
That completely explains it. 
How does NetJSON know which object (ID, Name) to put the values into?

Does the variable name have to match the field name?

**Comment by rpgmaker** [comment] 2015-07-31 01:28
the variable name have to match, but the case does not have to. As long as you set NetJSON.CaseSensitive = false.

If you want to deserialize into something that is unknown. I will say use DeserializeObject since it will return a Dictionary for you without having to create any class.

Thanks,

**Comment by dlonagh** [comment] 2015-07-31 01:47
I see. Thanks for clearing that out.

One problem with net3.5 version.
When I use "NetJSON.Deserialize" or any other methods in that class, the compiler doesn't recognize it as a class, but a namespace.
I have to write "NetJSON.NetJSON.Deserialize" for it to work. "using NetJSON" does not fix it.

Any ideas why?

**Comment by rpgmaker** [comment] 2015-07-31 02:02
Just include 

using NetJSON;

Before using it. The namespace and class just happened to be same, sorry.

Thanks,

**Comment by rpgmaker** [comment] 2015-07-31 02:04
I guess I can close this issue?

**Closed by rpgmaker** 2015-07-31 02:04 UTC

**Comment by dlonagh** [comment] 2015-07-31 02:11
" "using NetJSON" does not fix it. "

Can you try this and see if this issue is universal?

**Comment by rpgmaker** [comment] 2015-07-31 02:24
i guess since it does not work, it make sense because if the name is exactly the same thing. When the namespace is include, it allows the NetJSON class to be visible  but then the "using NetJSON" think it is using on a class. and it goes on and on.  

Generally, I use NetJSON.NetJSON.Whatever.

Thanks,
