### ISSUE TITLE
Failing in serialization with NullReferenceException

### ISSUE THREAD

**Issue by ocdogan** [rpgmaker/NetJSON#198] opened 2018-07-17 06:38 UTC
When using to serialize the array of WireMessage[] it is throwing null reference exception.

namespace Sweet.Actors
{
    public enum WireMessageState : byte
    {
        Default = 0,
        Canceled = 1,
        Completed = 2,
        Empty = 4,
        Faulted = 8
    }

    public enum MessageType
    {
        Default = 0,
        FutureMessage = 1,
        FutureResponse = 2,
        FutureError = 3
    }

    [Serializable]
    public class WireMessage
    {
        public string Id { get; set; }
        public WireMessageState State { get; set; }
        public MessageType MessageType { get; set; }
        public object Data { get; set; }
        public Dictionary<string, string> Header { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Exception Exception { get; set; }
        public int TimeoutMSec { get; set; }
    }
}

   at NetJSON.NetJSON.WriteDictionary(TypeBuilder typeBuilder, Type type, ILGenerator il)
   at NetJSON.NetJSON.WriteCollection(TypeBuilder typeBuilder, Type type, ILGenerator il)
   at NetJSON.NetJSON.WriteSerializeFor(TypeBuilder typeBuilder, Type type, ILGenerator methodIL)
   at NetJSON.NetJSON.WriteSerializeMethodFor(TypeBuilder typeBuilder, Type type, Boolean needQuote)
   at NetJSON.NetJSON.WritePropertyForType(TypeBuilder typeBuilder, ILGenerator il, LocalBuilder hasValue, Int32 counter, LocalBuilder name, Type propType, LocalBuilder propValue)
   at NetJSON.NetJSON.WritePropertiesFor(TypeBuilder typeBuilder, Type type, ILGenerator il, Boolean isPoly)
   at NetJSON.NetJSON.WriteSerializeFor(TypeBuilder typeBuilder, Type type, ILGenerator methodIL)
   at NetJSON.NetJSON.WriteSerializeMethodFor(TypeBuilder typeBuilder, Type type, Boolean needQuote)
   at NetJSON.NetJSON.WritePropertyForType(TypeBuilder typeBuilder, ILGenerator il, LocalBuilder hasValue, Int32 counter, LocalBuilder name, Type propType, LocalBuilder propValue)
   at NetJSON.NetJSON.WritePropertiesFor(TypeBuilder typeBuilder, Type type, ILGenerator il, Boolean isPoly)
   at NetJSON.NetJSON.WriteSerializeFor(TypeBuilder typeBuilder, Type type, ILGenerator methodIL)
   at NetJSON.NetJSON.WriteSerializeMethodFor(TypeBuilder typeBuilder, Type type, Boolean needQuote)
   at NetJSON.NetJSON.WriteListArray(TypeBuilder typeBuilder, Type type, ILGenerator il)
   at NetJSON.NetJSON.WriteCollection(TypeBuilder typeBuilder, Type type, ILGenerator il)
   at NetJSON.NetJSON.WriteSerializeFor(TypeBuilder typeBuilder, Type type, ILGenerator methodIL)
   at NetJSON.NetJSON.WriteSerializeMethodFor(TypeBuilder typeBuilder, Type type, Boolean needQuote)
   at NetJSON.NetJSON.GenerateTypeBuilder(Type objType, ModuleBuilder module)
   at NetJSON.NetJSON.Generate(Type objType)
   at NetJSON.NetJSON.NetJSONCachedSerializer`1.GetSerializer()
   at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor()

**Comment by rpgmaker** [comment] 2018-07-17 11:38
Thanks for the find. I will look into it this evening.

**Comment by rpgmaker** [comment] 2018-07-21 02:41
Can you remove the Exception object from the class and wrap it in a simple object?

**Comment by rpgmaker** [comment] 2018-07-31 00:49
I am going to go ahead and close this issue. The problem is lack of support for Exception at the moment. 

Please reopen if remove the exception object still fails for you.

Thanks,

**Closed by rpgmaker** 2018-07-31 00:49 UTC
