### ISSUE TITLE
Serialization problem

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#95] opened 2015-12-03 09:07 UTC
I have got strange problem with serializing rest request. First api call produces correct request:

``` json
 {"jsonrpc":"2.0","method":"SportsAPING/v1.0/listMarketBook","params":{"marketIds":["1.122110228"],"priceProjection":{"priceData":["EX_BEST_OFFERS"],"exBestOffersOverrides":{"bestPricesDepth":3}},"orderProjection":"ALL","matchProjection":"ROLLED_UP_BY_AVG_PRICE"},"id":1}
```
but following calls produce:

``` text
{jsonrpc:2.0,method:SportsAPING/v1.0/listMarketBook,params:{marketIds:[1.122110228],priceProjection:{priceData:[EX_BEST_OFFERS],exBestOffersOverrides:{bestPricesDepth:3}},orderProjection:ALL,matchProjection:ROLLED_UP_BY_AVG_PRICE},id:1}
```
``` text
{jsonrpc:2.0,method:SportsAPING/v1.0/listMarketBook,params:{marketIds:[1.122110228],priceProjection:{priceData:[EX_BEST_OFFERS,EX_TRADED],exBestOffersOverrides:{bestPricesDepth:10}},orderProjection:ALL,matchProjection:ROLLED_UP_BY_AVG_PRICE},id:1}
```

1.0.14 version of your library does not produce such failure behavior when serializing request data to json.

**Comment by rpgmaker** [comment] 2015-12-03 12:07
Quotes are missing?

**Comment by StefanBelo** [comment] 2015-12-03 12:10
Exactly, as you can see.

**Comment by rpgmaker** [comment] 2015-12-03 12:13
The issue is that I left threadstatic in the code after some changes. Sorry will fix today.

Thanks,

**Comment by StefanBelo** [comment] 2015-12-03 12:48
Thanks, I will test it then.

Couple weeks ago I had a strange problem. My app uses TPL to query not only main api data but some other sources as well, so requests are made on many threads.  

Sometimes my app frozen, I thought it was some cross threading problems, but having not exception thrown it was hardly to find a problem.

So I tried many different approaches with Async, but failed in all of them, then I switched to Newtonsoft.Json and all started working again, so it was not a problem in my code, but in your library, I used your old version 1.0.14.

Those days, I again tried your library, hoping you change something to solve my previous problem and found this serialization problem.

**Comment by rpgmaker** [comment] 2015-12-03 13:21
Try it again, it is fixed.

Thanks,

**Comment by StefanBelo** [comment] 2015-12-04 14:19
Serialization is fixed, but your library blocks/froze my app when using the above multi-threaded scenario, switching back Newtonsoft.Json and problems disappear.

What can be a problem in your library?

**Comment by rpgmaker** [comment] 2015-12-04 17:24
Does it work fine in the old version without freezing?

If so, stick to that version and I will compare it to what currently exists
in it.

Thanks,

**Comment by StefanBelo** [comment] 2015-12-04 17:59
No, it does not work on 1.0.14 nor the latest one you released.

**Comment by rpgmaker** [comment] 2015-12-04 18:03
So which work with multithreads?

Thanks,

**Comment by StefanBelo** [comment] 2015-12-04 18:21
None of your libraries works in my app in the scenario I needed to implement. I use Newtonsoft.Json at the moment.

**Comment by rpgmaker** [comment] 2015-12-04 18:31
I have not seen this issue with multithreads before. Can you explain what
you mean by it freezing?

Thanks,

**Comment by StefanBelo** [comment] 2015-12-04 19:06
http://bfexplorer.net/Community/BlogContent/141#Project Inspiration 4

Above you have got my app with similar use-case scenario, just watch video to understand how it works. In black is main app, and inn white (spreadsheet) a plugin with data delivery from the main app.

So it is a lot of data sources and data processing the app can handle, with such scenarios I use TPL to process any long time consuming jobs. The app is extendable by different ways. In one such project your library froze the app, when debugging I cannot see any expectations to be thrown.

As I said first I tried to find a bug in my code, reprogramming data querying and processing, after two days I tried everything I simply switched to another  json library and all worked/works again.

The app is mainly programmed in F# and data processing actually produces immutable objects, so common problems with multithreading locks is out of option.

I do not say that it is multithreading what causes problems in your library, what I can see only that your library fails in such use case scenario, and other library Newtonsoft.Json works fine.

It is hard to find json data sample which causes problems with your library as app monitors data in 50 mili seconds intervals.

**Comment by rpgmaker** [comment] 2015-12-04 19:11
So I should be able to reproduce it if I use tpl and try to serialize and
deserialize in different tasks, right?

Will it be possible to give me an example logic in F# that I can use for my
testing. The type of data does not matter.

Thanks,

**Comment by binis2** [comment] 2015-12-07 16:38
I can confirm that there is something smelly with multi-threading and NetJSON. On heavy load deserializing complex JSON structures corrupts the callstack and crashing the application in a nasty way. Changing the JSON library make the problem go away.

When I find spare time I will try to reproduce the problem in a test case and will send it to you.

**Comment by rpgmaker** [comment] 2015-12-07 16:46
Thanks a lot. I really appreciate that.

**Comment by rpgmaker** [comment] 2015-12-24 06:06
Closing this issue. Please create a new issue that describes the multithread issue you encountered. 

Thanks,

**Closed by rpgmaker** 2015-12-24 06:06 UTC

**Comment by rpgmaker** [comment] 2016-01-05 00:50
I think I figured out why the problem exists. It might have to do with using a lot of GetOrAdd method of the concurrent dictionary which delegate is not threadsafe because is not synchronized with the lock of concurrent dictionary. I will try to replicate the problem and then see if adding locks will help

Thanks,

**Comment by rpgmaker** [comment] 2016-02-28 08:16
Can one of you test the multithread scenario again using the latest version and let me know if you are still encounter the same issue.

Thanks,

**Comment by binis2** [comment] 2016-02-29 09:32
OK. Starting it right away. It will take some time thou.

**Comment by rpgmaker** [comment] 2016-02-29 23:37
Thanks. You can take your time. There is no rush

**Comment by binis2** [comment] 2016-04-12 11:53
Sorry for the late response. I did some really extensive testing and it seems that things are working fine  now. Thx for your effort and keep up the good work.

**Comment by rpgmaker** [comment] 2016-04-12 13:25
Thanks for the help. Really appreciate it.
